# Generated by Django 5.0.3 on 2024-09-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kategorii')),
                ('name_pl', models.CharField(max_length=255, null=True, verbose_name='Nazwa kategorii')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nazwa kategorii')),
                ('slug', models.CharField(editable=False, max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa produktu')),
                ('name_pl', models.CharField(max_length=255, null=True, verbose_name='Nazwa produktu')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nazwa produktu')),
                ('slug', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa wariantu')),
                ('name_pl', models.CharField(max_length=255, null=True, verbose_name='Nazwa wariantu')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nazwa wariantu')),
                ('stock_code', models.CharField(max_length=255, unique=True, verbose_name='Kod magazynowy')),
                ('unit_price', models.FloatField(verbose_name='Cena')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Wariant produktu',
                'verbose_name_plural': 'Warianty produktów',
            },
        ),
    ]
