[tool.isort]
py_version = 310
profile = "black"
atomic = true
combine_star = true
honor_noqa = true
force_single_line = true
order_by_type = true
lines_before_imports = 1
default_section = "THIRDPARTY"
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_django = "Django"
import_heading_thirdparty = "3rd-party"
import_heading_firstparty = "Project"
import_heading_localfolder = "Local"
known_django = "django"
known_first_party = ["apps.*"]
known_local_folder = ["core", "project", "accounts"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = ["backend/apps/*/migrations/*.py", "migrations/*.py", "migrations/*", "migrations/"]
skip = ["migrations"]

[tool.pycln]
all = true
path = "./"

[tool.flake8]
max-line-length = 99
select = ["C", "E", "F", "W", "B", "B950"]
exclude = ["*/migrations/*"]
