# Generated by Django 5.0.3 on 2024-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa sklepu')),
                ('show_current_month_orders_chart', models.BooleanField(default=True, verbose_name='Pokaż wykres zamówień z aktualnego miesiąca')),
                ('show_last_12_months_orders_chart', models.BooleanField(default=True, verbose_name='Pokaż wykres zamówień z ostatnich 12 miesięcy')),
                ('show_countries_orders_chart', models.BooleanField(default=True, verbose_name='Pokaż wykres zamówień z konkretnych krajów')),
                ('show_categories_products_chart', models.BooleanField(default=True, verbose_name='Pokaż wykres produktów z konkretnych kategorii')),
                ('show_best_sells_products_chart', models.BooleanField(default=True, verbose_name='Pokaż wykres najlepiej sprzedających się produktów')),
                ('enable_test_mode', models.BooleanField(default=False, help_text='Tryb testowy pozwala na wymianę WSZYSTKICH danych w bazie danych (w celach pokazowych', verbose_name='Włącz tryb testowy')),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
    ]
