# Generated by Django 5.0.3 on 2024-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_products_stats',
            field=models.BooleanField(default=True, verbose_name='Pokaż tabelę ze statystykami produktów'),
        ),
    ]
