# Generated by Django 5.0.3 on 2024-09-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('new_arrival', 'Nowość'), ('best_seller', 'Najlepiej sprzedający się'), ('discounted', 'Przeceniony'), ('limited_edition', 'Edycja limitowana'), ('eco_friendly', 'Ekologiczny'), ('premium_quality', 'Wysoka jakość'), ('on_sale', 'Na wyprzedaży'), ('exclusive', 'Ekskluzywny'), ('trending', 'Trendy'), ('top_rated', 'Najwyżej oceniany'), ('seasonal', 'Sezonowy'), ('gift_idea', 'Pomysł na prezent'), ('handmade', 'Ręcznie robiony'), ('low_stock', 'Niski stan magazynowy'), ('best_value', 'Najlepsza wartość')], max_length=15, verbose_name='Tag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Tag produktu',
                'verbose_name_plural': 'Tagi produktów',
            },
        ),
    ]
