# Generated by Django 5.0.3 on 2024-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa')),
                ('name_pl', models.CharField(max_length=64, null=True, unique=True, verbose_name='Nazwa')),
                ('name_en', models.CharField(max_length=64, null=True, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Państwo',
                'verbose_name_plural': 'Państwa',
            },
        ),
    ]
